### ISSUE TITLE
Fail on missing snapshot

### ISSUE THREAD

**Issue by serl** [bmihelac/pytest-image-snapshot#1]
I'm running this plugin in CI, and it's fantastic!

A little problem that I have is that I'd like the tests to fail if a screenshot is missing (but only in CI, locally I really like the fact that's just creating the missing ones).
What about adding some `--image-snapshot-fail-if-missing`?

I'd prepare a PR if you think that fits. (I mean otherwise I can continue with `git diff --exit-code` as well...)

**Comment by bmihelac** [comment]
@serl seems logic, I'll be glad to merge PR
